# Generated by Django 2.2.3 on 2019-07-26 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=10, verbose_name='短网址 hash')),
                ('original_url', models.CharField(max_length=10, verbose_name='源地址')),
                ('is_expired', models.BooleanField(default=False, verbose_name='标识是否过期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '短网址',
                'verbose_name_plural': '短网址',
                'ordering': ['-created_at'],
            },
        ),
    ]
