# Generated by Django 2.2.3 on 2019-07-27 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
