# Generated by Django 2.2.3 on 2019-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_shorturlmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
    ]
